### ISSUE TITLE
Correct way to update map style?

### ISSUE THREAD

**Issue by jakob-fuchs** [maptalks/maptalks.mapboxgl#9]
I'm trying to update the style of my base layer, these two methods work but they add a new layer instead of updating the existing one:

```javascript
        map.setBaseLayer(new MapboxglLayer('map', {
          glOptions: {
            style: selectedStyleUrl,
          }
        }));
```

```javascript
        const baseLayer = map.getBaseLayer();
        baseLayer.config({
          glOptions: {
            style: selectedStyleUrl,
          }
        });
        baseLayer.load();
```

So I always end up with a lot of layers, which is not desirable for performance reasons. Any ideas how I can fix that?

I can go into the DOM manually and remove the layer but that doesn't seem to be the best solution. `baseLayer.remove()` doesn't seem to fix this.

**Comment by jakob-fuchs** [comment]
Thanks a lot, that worked:

```javascript
map.getBaseLayer().getGlMap().setStyle(styleUrl)
```

**Comment by panuairspace** [comment]
> Thanks a lot, that worked:
> 
> ```js
> map.getBaseLayer().getGlMap().setStyle(styleUrl)
> ```

Hi guys,

I think I have the same problem with @jakob-fuchs, but what I intended to do was to change from 

var map = new maptalks.Map("map",{
        //limit max pitch to 60 as mapbox-gl-js required
        center: [-74.0066, 40.7135],
        zoom: 15.5,
        pitch: 45,
        bearing: -17.6,
        container: 'map',
        baseLayer: new maptalks.TileLayer('base', {
          urlTemplate: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
          subdomains: ['a','b','c','d'],
          attribution: '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>'
        })
    });

to this one.

map = new maptalks.Map("map",{
          center: [-74.0066, 40.7135],
          zoom: 15.5,
          pitch: 45,
          bearing: -17.6,
          container: 'map',
          baseLayer: mapboxglLayer
        });

because I needed mapboxBase to render some style from mapbox.

I way that I'm using right now is map.remove() and new map again. But it seems to mess up with some part of the code, I'n not sure if you guys have any suggestion?

"map.getBaseLayer().getGlMap().setStyle(styleUrl)" doesn't work for me.
![image](https://user-images.githubusercontent.com/51385691/59705869-19881400-91b4-11e9-90ac-15252f051a7c.png)

Thank you!
